Various features and bug fixes
ITK-Leantime/leantime-timetable pull request #31
Opened 2024-11-19 13:49 UTC by jeppekroghitk

- **Created new handler to handle post cases**
- **Revised date navigation logic to be more flexible and revised post handler, introducing previously added helper**
- **Added new translations**
- **Added ticket type to select**
- **Refactored table rendition and cleaned up**
- **Fixed bugs, added new date range selector, optimizations etc**
- **Built dist files**
- **Added flatpickr**

#### Link to ticket

Please add a link to the ticket being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2025-01-09 10:21 UTC, cableman requested changes

2025-01-09 10:21 UTC, cableman commented on Controllers/Settings.php
> +            $ticketCacheExpiration = (int) ($this->settingsRepo->getSetting('itk-leantime-timetable.ticketCacheExpiration') ?: 60);
Should the fallback number "60" be defined as a class const?

2025-01-09 10:21 UTC, cableman commented on Controllers/TimeTable.php
> +            switch ($_POST['action']) {
As this assigned an return value in each case "$redirectUrl" it could be written as a match statement.

2025-01-09 10:21 UTC, cableman commented on Controllers/TimeTable.php
> +        try {
All this date handling should possibly, be handle with the data time helpers from https://github.com/Leantime/leantime/blob/master/app/Core/Support/DateTimeHelper.php 


Not sure about this, as I have lost overview over the date stuff.

2025-01-09 10:21 UTC, cableman commented on Controllers/TimeTable.php
> +            echo 'Invalid Date: ' . $e->getMessage();
Should this be an exception? That would end in a 500 error.

2025-01-09 10:21 UTC, cableman commented on Helpers/TimeTableActionHandler.php
> +     * Adjusts the period based on the provided POST data.
Maybe a comment about why this adjustment is needed?

2025-01-09 10:21 UTC, cableman commented on Helpers/TimeTableActionHandler.php
> +            $redirectUrl .= (!str_contains($redirectUrl, '?') ? '?' : '&') . http_build_query($queryParams);
Maybe https://www.php.net/manual/en/function.parse-url.php with the http_build_query could make this a little more readable and secure?

2025-01-09 13:08 UTC, jeppekroghitk commented on Controllers/TimeTable.php
> +        try {
I have allowed certain cases for date get params, so it's kind of a custom solution. Im not sure much good will come out of utilizing the DateTimeHelper.

2025-01-10 08:25 UTC, cableman approved these changes

2025-01-10 11:32 UTC, merged